black/himloco:  #机器人名/配置名
  num_observations: 45  #单帧观测维度：3维命令（x,y方向上的命令和旋转的命令），3维角速度，3维重力向量
                        #在自身坐标系下的投影，12维关节角度，12维关节角速度，12维上一帧动作，加一起45
  observations: ["commands","ang_vel", "gravity_vec", "dof_pos", "dof_vel", "actions"]
                        #单帧观测由哪几项，按什么顺序拼（和训练一致）
  observations_history: [0,1,2,3,4,5]   #取6帧，总输入270维

  #进rl后的kp和kd（与训练时一致）
  rl_kp: [40.0, 40.0, 40.0,
          40.0, 40.0, 40.0,
          40.0, 40.0, 40.0,
          40.0, 40.0, 40.0]
  rl_kd: [1.2, 1.2, 1.2,
          1.2, 1.2, 1.2,
          1.2, 1.2, 1.2,
          1.2, 1.2, 1.2]
  action_scale: [0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25]  #网络输出乘以这个系数，再叠加到default_pos上
  lin_vel_scale: 2.0                #线速度缩放
  ang_vel_scale: 0.25               #角速度缩放
  dof_pos_scale: 1.0                #关节角（相对于defalut_pos的偏差）缩放
  dof_vel_scale: 0.05               #关节角速度缩放
  commands_scale: [2.0, 2.0, 0.25]  #命令【vx,vy,角度】的缩放
  torque_limits: [33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5] #力矩限幅
  #站立姿态12个关节角（策略顺序）
  default_dof_pos: [0.0, 0.8014, -1.527, -0.0, -0.8014, 1.527, 0.0, 0.8014, -1.527, -0.0, -0.8014, 1.527]
  model_name: "best.pt"           #加载的模型名字
  num_of_dofs: 12                 #关节数量
  clip_obs: 100.0                 #观测限幅
  joint_mapping: [0,1,2,3,4,5, 9,10,11, 6,7,8]   #策略第i个关节->下游数组第几个元素 

  #起身/趴下姿态插值阶段用的增益
  fixed_kp: [40,40,40,40,
             40,40,40,40,
             40,40,40,40]              
  fixed_kd: [1.2,1.2,1.2,1.2,
             1.2,1.2,1.2,1.2,
             1.2,1.2,1.2,1.2]            
  wheel_indices: []              #轮子用

  #动作限幅（因为网格问题其实等于不限幅）
  clip_actions_lower: [-100,-100,-100,-100,
                       -100,-100,-100,-100,
                       -100,-100,-100,-100]
  clip_actions_upper: [ 100,100,100,100,
                        100,100,100,100,
                        100,100,100,100]