black:
  dt: 0.005
  decimation: 4
  num_of_dofs: 12
  wheel_indices: [] 
  fixed_kp: [40.0, 40.0, 40.0,
          40.0, 40.0, 40.0,
          40.0, 40.0, 40.0,
          40.0, 40.0, 40.0]
  fixed_kd: [1.2, 1.2, 1.2,
          1.2, 1.2, 1.2,
          1.2, 1.2, 1.2,
          1.2, 1.2, 1.2]
  torque_limits: [33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5]
  joint_names: [FL_hip_joint, FL_thigh_joint, FL_calf_joint,
                FR_hip_joint, FR_thigh_joint, FR_calf_joint,
                RL_hip_joint, RL_thigh_joint, RL_calf_joint,
                RR_hip_joint, RR_thigh_joint, RR_calf_joint]
  default_dof_pos: [0.0, 0.8014, -1.527, -0.0, -0.8014, 1.527, 0.0, 0.8014, -1.527, -0.0, -0.8014, 1.527]
  joint_controller_names: [FL_hip_joint, FL_thigh_joint, FL_calf_joint,
                           FR_hip_joint, FR_thigh_joint, FR_calf_joint,
                           RR_hip_joint, RR_thigh_joint, RR_calf_joint,
                           RL_hip_joint, RL_thigh_joint, RL_calf_joint]
  joint_mapping: [0,1,2,3,4,5,9,10,11,6,7,8]
